repos:
# =============================================================================
# Formatters and Linters
# =============================================================================
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.13
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

# =============================================================================
# uv Specific
# =============================================================================
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.7.13
  hooks:
    # Update the uv lockfile
    - id: uv-lock